### ISSUE TITLE
Cannot select items which aren't visible initially 

### ISSUE THREAD

**Issue by mariotebest** [DCCS-IT-Business-Solutions/react-searchable-select-mui#4]
Reproduction steps:

1. use an options array with ~ 100 options.
2. use `showAll = false`
3. select an option which isn't shown in the initial select (i.e. the option with id: 100)

The option cannot be selected because of the following error:

![image](https://user-images.githubusercontent.com/54019893/67746317-86df6780-fa26-11e9-9715-c046cc50c96b.png)

Current workaround: set `showall `to `true`

**Comment by mvitzthum** [comment]
Should be fixed in Version 0.2.10.
Please check and close if it works :)
